# Generated by Django 3.0.8 on 2023-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Product', max_length=200)),
                ('lname', models.CharField(default='Product', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_going', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'invited',
            },
        ),
    ]
