# Generated by Django 3.2.19 on 2023-05-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited',
            name='fname',
            field=models.CharField(default='sam', max_length=200),
        ),
        migrations.AlterField(
            model_name='invited',
            name='lname',
            field=models.CharField(default='john', max_length=200),
        ),
    ]
